name: chilldrive
description: "Découvrez CHILLCar, l'application mobile innovante qui révolutionne la location de voitures, offrant une expérience fluide, sécurisée et ultra-moderne pour louer le véhicule de vos rêves en quelques clics."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  shared_preferences: ^2.0.0
  flutter_rating_bar: ^4.0.0
  url_launcher: ^6.0.0
  flutter_map: ^8.0.0
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
